t=(10,20,30,40,50,60,70,80,90,100)
print("Tuple elements:")
print(t)
print("First Five elements:")
print(t[0:5])
print("Last Five elements:")
print(t[len(t)-1:4:-1])
print("Middle elements:")
print(t[3:7])
print("Alante elements:")
print(t[::2])
print("Reverse elements:")
print(t[::-1])
print("Conversion of tuple to list elements:")
v=list(t)
print(v)
